server:
  port: 8080
  servlet:
    context-path: /chacha
spring:
  profiles:
    active: dev
  security:
    user:
      name: chacha
      password: 123456
management:
  server:
    port: 8090
    servlet:
      context-path: /sys
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'