server:
  port: 8080
  servlet:
    context-path: /chacha
spring:
  profiles:
    active: dev
  application:
    # Spring Boot Admin client project name
    name: spring-boot-learning-admin-client
  boot:
    admin:
      client:
        # Spring Boot Admin server location
        url: "http://localhost:8000"
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  security:
    user:
      name: chacha
      password: 123456
management:
  server:
    port: 8090
    servlet:
      context-path: /sys
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'